###
GET http://localhost:8081/

###
POST http://localhost:8081/login
Accept: application/json
Authorization: Basic manager_1 01_manager_01

###
POST http://localhost:8081/login
Accept: application/json
Authorization: Basic bryan password

###
GET http://localhost:8081/customers
Accept: application/json

### Get users as manager
GET http://localhost:8081/customers
Accept: application/json
# Token generated with manager account.
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDE5OTgzNDZ9.IoJywDJUqXx7dLoe1IxeuGWz-RQyG1TG_D_Sx1nPqO6xWxB8lwrr1vDO9JpbSI-HHTz6Sx3UdqD7ZqsyKZBkYw

### Get users as analyst
GET http://localhost:8081/customers
Accept: application/json
# Token generated with analyst account.
Authorization: Bearer ...

### Create new user
POST http://localhost:8081/customers
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDE5OTgzNDZ9.IoJywDJUqXx7dLoe1IxeuGWz-RQyG1TG_D_Sx1nPqO6xWxB8lwrr1vDO9JpbSI-HHTz6Sx3UdqD7ZqsyKZBkYw

{
    "full_name":"Mark Tan",
    "nric":"S8291266I",
    "phone":"91251234",
    "address":"27 Jalan Alamak S680234",
    "username":"bryan",
    "password":"password",
    "authorities":"ROLE_USER",
    "active": true
}

### Update a user
PUT http://localhost:8081/customers/16
Content-Type: application/json
# User token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6MTYsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2MDIwMDAxMDJ9.qs3Zmm3yAosjF0FrEC94K0zXuK7zHMObGTk3VQOunAJHUNWly8ldcuIfLDC7sMcvSMS4b3xVvivxA_qQkzHEPw
# Manager token
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDE5OTgzNDZ9.IoJywDJUqXx7dLoe1IxeuGWz-RQyG1TG_D_Sx1nPqO6xWxB8lwrr1vDO9JpbSI-HHTz6Sx3UdqD7ZqsyKZBkYw

{
    "nric":"S8291265Z",
    "phone":"98199189"
}

### Get user info
GET http://localhost:8081/customers/16
Content-Type: application/json
# User token
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnlhbiIsInVpZCI6MTYsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2MDIwMDAxMDJ9.qs3Zmm3yAosjF0FrEC94K0zXuK7zHMObGTk3VQOunAJHUNWly8ldcuIfLDC7sMcvSMS4b3xVvivxA_qQkzHEPw
# Manager token
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyXzEiLCJ1aWQiOjEsImF1dGgiOiJST0xFX01BTkFHRVIiLCJleHAiOjE2MDE5OTgzNDZ9.IoJywDJUqXx7dLoe1IxeuGWz-RQyG1TG_D_Sx1nPqO6xWxB8lwrr1vDO9JpbSI-HHTz6Sx3UdqD7ZqsyKZBkYw
