###
GET http://localhost:8081/

###
POST http://localhost:8081/login
Accept: application/json

{
    "username": "manager_1",
    "password": "01_manager_01"
}

###
POST http://localhost:8081/login
Accept: application/json

{
    "username": "analyst_1",
    "password": "01_analyst_01"
}

###
GET http://localhost:8081/users
Accept: application/json

###
GET http://localhost:8081/users
Accept: application/json
# Token generated with manager account.
Authorization: Bearer ...

###
GET http://localhost:8081/users
Accept: application/json
# Token generated with analyst account.
Authorization: Bearer ...

